/**
 * Copyright (c) 2018 The xterm.js authors. All rights reserved.
 * @license MIT
 */

import { IRenderDimensions } from 'browser/renderer/shared/Types';
import { IThemeService } from 'browser/services/Services';
import { Disposable, toDisposable } from 'common/Lifecycle';
import { IColor } from 'common/Types';
import { Terminal } from '@xterm/xterm';
import { ICursorRenderModel, IRenderModel } from './Types';
import { createBlendState, GPU_BUFFER_USAGE } from './WebgpuUtils';
import type { ILogService } from 'common/services/Services';

const MAX_CURSOR_RECTANGLES = 4;
const FLOATS_PER_RECTANGLE = 8;
const CURSOR_UNIFORM_BYTES = MAX_CURSOR_RECTANGLES * FLOATS_PER_RECTANGLE * Float32Array.BYTES_PER_ELEMENT;

interface ICursorUniformState extends ICursorRenderModel {
  readonly canvasWidth: number;
  readonly canvasHeight: number;
  readonly colorVersion: number;
}

const shaderSource = `
struct CursorRectangle {
  positionAndSize: vec4f,
  color: vec4f,
}
struct CursorUniforms {
  rectangles: array<CursorRectangle, ${MAX_CURSOR_RECTANGLES}>,
}
struct VertexOutput {
  @builtin(position) position: vec4f,
  @location(0) color: vec4f,
}

@group(0) @binding(0) var<uniform> cursor: CursorUniforms;

fn quad(vertexIndex: u32) -> vec2f {
  return array<vec2f, 4>(vec2f(0.0, 0.0), vec2f(1.0, 0.0), vec2f(0.0, 1.0), vec2f(1.0, 1.0))[vertexIndex];
}

@vertex
fn vertexMain(@builtin(vertex_index) vertexIndex: u32, @builtin(instance_index) instanceIndex: u32) -> VertexOutput {
  let rectangle = cursor.rectangles[instanceIndex];
  let zeroToOne = rectangle.positionAndSize.xy + quad(vertexIndex) * rectangle.positionAndSize.zw;
  var output: VertexOutput;
  output.position = vec4f(zeroToOne.x * 2.0 - 1.0, 1.0 - zeroToOne.y * 2.0, 0.0, 1.0);
  output.color = rectangle.color;
  return output;
}

@fragment
fn fragmentMain(input: VertexOutput) -> @location(0) vec4f {
  return input.color;
}`;

export class RectangleRenderer extends Disposable {
  private readonly _cursorBuffer: GPUBuffer;
  private readonly _cursorBindGroup: GPUBindGroup;
  private readonly _cursorBundle: GPURenderBundle;
  private readonly _cursorBundles: GPURenderBundle[];
  private readonly _cursorData = new Float32Array(MAX_CURSOR_RECTANGLES * FLOATS_PER_RECTANGLE);
  private _cursorVisible = false;
  private _cursorBufferDirty = true;
  private _cursorUploadBytes = 0;
  private _cursorFloat!: Float32Array;
  private _cursorColorVersion = 0;
  private _cursorState: ICursorUniformState | undefined;

  constructor(
    _terminal: Terminal,
    private readonly _device: GPUDevice,
    canvasFormat: GPUTextureFormat,
    private _dimensions: IRenderDimensions,
    themeService: IThemeService,
    _logService: ILogService
  ) {
    super();
    const shaderModule = this._device.createShaderModule({ label: 'xterm cursor shader', code: shaderSource });
    const pipeline = this._device.createRenderPipeline({
      label: 'xterm cursor pipeline',
      layout: 'auto',
      vertex: { module: shaderModule, entryPoint: 'vertexMain' },
      fragment: {
        module: shaderModule,
        entryPoint: 'fragmentMain',
        targets: [{ format: canvasFormat, blend: createBlendState() }]
      },
      primitive: { topology: 'triangle-strip' }
    });
    this._cursorBuffer = this._device.createBuffer({
      label: 'xterm cursor uniforms',
      size: CURSOR_UNIFORM_BYTES,
      usage: GPU_BUFFER_USAGE.UNIFORM | GPU_BUFFER_USAGE.COPY_DST
    });
    this._cursorBindGroup = this._device.createBindGroup({
      label: 'xterm cursor bind group',
      layout: pipeline.getBindGroupLayout(0),
      entries: [{ binding: 0, resource: { buffer: this._cursorBuffer } }]
    });
    const encoder = this._device.createRenderBundleEncoder({
      label: 'xterm cursor render bundle',
      colorFormats: [canvasFormat]
    });
    encoder.setPipeline(pipeline);
    encoder.setBindGroup(0, this._cursorBindGroup);
    encoder.draw(4, MAX_CURSOR_RECTANGLES);
    this._cursorBundle = encoder.finish();
    this._cursorBundles = [this._cursorBundle];
    this._register(toDisposable(() => this._cursorBuffer.destroy()));

    this._updateCachedColor(themeService.colors.cursor);
    this._register(themeService.onChangeColors(colors => this._updateCachedColor(colors.cursor)));
  }

  public renderCursor(pass: GPURenderPassEncoder): void {
    if (!this._cursorVisible) {
      return;
    }
    if (this._cursorBufferDirty) {
      this._device.queue.writeBuffer(this._cursorBuffer, 0, this._cursorData);
      this._cursorBufferDirty = false;
      this._cursorUploadBytes += this._cursorData.byteLength;
    }
    pass.executeBundles(this._cursorBundles);
  }

  public get cursorUploadBytes(): number { return this._cursorUploadBytes; }

  public handleResize(): void {
    // Position data is regenerated by updateCursor after a renderer resize.
  }

  public setDimensions(dimensions: IRenderDimensions): void {
    this._dimensions = dimensions;
  }

  public updateCursor(model: IRenderModel): void {
    const cursor = model.cursor?.style === 'bar' || model.cursor?.style === 'underline' || model.cursor?.style === 'outline'
      ? model.cursor
      : undefined;
    if (cursorStateEquals(this._cursorState, cursor, this._dimensions, this._cursorColorVersion)) {
      return;
    }
    this._cursorState = cursor ? {
      ...cursor,
      canvasWidth: this._dimensions.device.canvas.width,
      canvasHeight: this._dimensions.device.canvas.height,
      colorVersion: this._cursorColorVersion
    } : undefined;
    this._cursorData.fill(0);
    let rectangleCount = 0;
    if (cursor && (cursor.style === 'bar' || cursor.style === 'outline')) {
      this._addRectangle(
        this._cursorData,
        rectangleCount++,
        cursor.x * this._dimensions.device.cell.width,
        cursor.y * this._dimensions.device.cell.height,
        cursor.style === 'bar' ? cursor.dpr * cursor.cursorWidth : cursor.dpr,
        this._dimensions.device.cell.height
      );
    }
    if (cursor && (cursor.style === 'underline' || cursor.style === 'outline')) {
      this._addRectangle(
        this._cursorData,
        rectangleCount++,
        cursor.x * this._dimensions.device.cell.width,
        (cursor.y + 1) * this._dimensions.device.cell.height - cursor.dpr,
        cursor.width * this._dimensions.device.cell.width,
        cursor.dpr
      );
    }
    if (cursor?.style === 'outline') {
      this._addRectangle(
        this._cursorData,
        rectangleCount++,
        cursor.x * this._dimensions.device.cell.width,
        cursor.y * this._dimensions.device.cell.height,
        cursor.width * this._dimensions.device.cell.width,
        cursor.dpr
      );
      this._addRectangle(
        this._cursorData,
        rectangleCount++,
        (cursor.x + cursor.width) * this._dimensions.device.cell.width - cursor.dpr,
        cursor.y * this._dimensions.device.cell.height,
        cursor.dpr,
        this._dimensions.device.cell.height
      );
    }
    this._cursorVisible = rectangleCount > 0;
    this._cursorBufferDirty = true;
  }

  private _addRectangle(target: Float32Array, index: number, x: number, y: number, width: number, height: number): void {
    const offset = index * FLOATS_PER_RECTANGLE;
    target[offset] = x / this._dimensions.device.canvas.width;
    target[offset + 1] = y / this._dimensions.device.canvas.height;
    target[offset + 2] = width / this._dimensions.device.canvas.width;
    target[offset + 3] = height / this._dimensions.device.canvas.height;
    target.set(this._cursorFloat, offset + 4);
  }

  private _updateCachedColor(color: IColor): void {
    this._cursorFloat = new Float32Array([
      ((color.rgba >> 24) & 0xFF) / 255,
      ((color.rgba >> 16) & 0xFF) / 255,
      ((color.rgba >> 8) & 0xFF) / 255,
      (color.rgba & 0xFF) / 255
    ]);
    this._cursorColorVersion++;
  }
}

function cursorStateEquals(
  previous: ICursorUniformState | undefined,
  current: ICursorRenderModel | undefined,
  dimensions: IRenderDimensions,
  colorVersion: number
): boolean {
  if (!previous || !current) {
    return previous === current;
  }
  return previous.x === current.x &&
    previous.y === current.y &&
    previous.width === current.width &&
    previous.style === current.style &&
    previous.cursorWidth === current.cursorWidth &&
    previous.dpr === current.dpr &&
    previous.canvasWidth === dimensions.device.canvas.width &&
    previous.canvasHeight === dimensions.device.canvas.height &&
    previous.colorVersion === colorVersion;
}
